let singletoneRequire = require('../lib/SingletonRequirer.js')(runtime, this)
let runningQueueDispatcher = singletoneRequire('RunningQueueDispatcher')(runtime, this)

runningQueueDispatcher.showDispatchStatus()
runningQueueDispatcher.addRunningTask()
sleep(500)
runningQueueDispatcher.showDispatchStatus()
runningQueueDispatcher.addRunningTask()
sleep(500)
runningQueueDispatcher.showDispatchStatus()
runningQueueDispatcher.removeRunningTask()
sleep(500)
runningQueueDispatcher.showDispatchStatus()
// runningQueueDispatcher.clearAll()

