let singletonRequire = require('../lib/SingletonRequirer.js')(runtime, this)
let runningQueueDispatcher = singletonRequire('RunningQueueDispatcher')

runningQueueDispatcher.showDispatchStatus()
runningQueueDispatcher.addRunningTask()
sleep(500)
runningQueueDispatcher.showDispatchStatus()
runningQueueDispatcher.addRunningTask()
sleep(500)
runningQueueDispatcher.showDispatchStatus()
runningQueueDispatcher.removeRunningTask()
sleep(500)
runningQueueDispatcher.showDispatchStatus()
// runningQueueDispatcher.clearAll()

